### ISSUE TITLE
Row padding cannot be omitted 

### ISSUE THREAD

**Issue by britisharmy** [a-tokyo/react-native-flex-grid#15]
Is there a way i can omit the padding around rows? There is too much space on the left and right of the row.

**Comment by a-tokyo** [comment]
Yes! You can pass `gx={0}` as a prop, just like in [Bootstrap Gutters](https://getbootstrap.com/docs/5.0/layout/gutters/).

You can check the code docs here:
Row: https://github.com/a-tokyo/react-native-flex-grid/blob/main/src/components/Layout/Row/Row.tsx
Col: https://github.com/a-tokyo/react-native-flex-grid/blob/main/src/components/Layout/Col/Col.tsx

I will work soon on adding this doc to the README, thanks for opening the issue! Please reopen if you have further questions

**Comment by a-tokyo** [comment]
added documentation here: https://github.com/a-tokyo/react-native-flex-grid#component-props---can-be-used-to-customize-layout-components
