### ISSUE TITLE
Order functionality is not working as expected

### ISSUE THREAD

**Issue by Yasas4D** [a-tokyo/react-native-flex-grid#16]
**Describe the bug**
The ordering functionality is not working as expected. When attempting to reorder columns, the desired behaviour does not occur.

**To Reproduce**
    1. Create three different columns with labels: "first," "second," and "third"
    2. Set the initial order of the columns as "first, second, third"
    3. Attempt to reorder the columns to "second, third, first" using "smOrder"
    4. Observe that the columns do not reorder correctly. 

**Expected behavior**
The columns should be able to be reordered according to the specified order, resulting in "second, third, first" as the final order.

**Screenshots**
![image](https://github.com/a-tokyo/react-native-flex-grid/assets/49401137/3834f5f7-a3a4-44ce-8d33-cda5f3fbba28)

**Smartphone**

- Device: Google Pixel 4
- OS: Android 11 x86 API 30
- react-native Version: 0.68.2

**Comment by a-tokyo** [comment]
Hey @Yasas4D ! Thanks for the report

I am on leave for the next 2 weeks, I can def fix this after.
The code is quite easy tho, so if you're into it you can open a PR! This is the file that we should work on https://github.com/a-tokyo/react-native-flex-grid/blob/main/src/components/Layout/Col/Col.tsx

**Comment by a-tokyo** [comment]
I couldn't reproduce this on rn 0.72, so I believe this is due to RN 0.68 not supporting the `Flex Order` property which is currently supported by RN https://www.tutorialspoint.com/how-to-use-flexbox-in-react-native.

Upgrading RN is the best option, another way around this is to do it with JS logic instead of flex styles.

**Comment by Yasas4D** [comment]
Thank you very much @a-tokyo I will check this on RN 0.72
